### ISSUE TITLE
Don't use blueprints for this app

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/airtng-flask#5]
Blueprints are helpful on larger Flask apps, but they also make the source code more difficult to understand.

In retrospect, we should have built this app using [Django](https://www.djangoproject.com/). It's easier to manage larger projects with Django than with Flask.

For now, though, let's just remove the blueprints feature from this app. That should simplify your `views.py` and a few other files.

**Comment by nebtrx** [comment]
I'm using blueprints in this app in order to tests views properly(redirect, templates used), otherwise I can't import views in the context of tests without having conflicts.

**Comment by atbaker** [comment]
Have you looked at the testing page in the Flask docs?

http://flask.pocoo.org/docs/0.10/testing/

This page describes how to test a Flask app (including views) without use blueprints. I noticed you're using Flask-Testing - it should work without blueprints too.

I really think blueprints make this app difficult for a new developer to understand. Can you please give it a try?

If it still doesn't work, I can live with removing some tests if that's what it takes to remove the blueprints.

**Comment by nebtrx** [comment]
Yes I really like a lot of times, in fact it kind of become an obsessions to achieve that(check my progression on the 4 flask tutorial triying to achieve that).  The thing is docs tells you how to test it, but when you put the hands on it you realize that going throw the test command and creating a test app, your views are not really loaded and then tests start failing because templates are not loaded, and you can't import there views without getting errors(in fact I started creating init methods for reusing the modules). The only way to do that would be to reuse the dev app and therefore environment db, which it's not a good practice. Take a time to think about what I'm saying, I may lose something on the way, but I really pushed to achieve that without blueprints. If it's ok to you to miss view tests at this point, I don't mind.

**Comment by atbaker** [comment]
Okay - in that case let's remove the blueprints and also remove any tests that break. We won't worry about coverage for this app.

Thanks again for working on this.

**Comment by nebtrx** [comment]
Don't mention it. Done!
